/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidad.Cliente;
import Entidad.Libro;
import Entidad.MSG;
import Entidad.Venta;
import Interfaces.ICliente;
import Interfaces.ILibro;
import Interfaces.IVenta;
import Servicios.cliente_servicio;
import Servicios.libro_servicio;
import Servicios.venta_servicio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mati Droid
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    double iva = 0;
    ICliente icliente;
    ILibro ilibro;
    IVenta iventa;
    String[][] matriz = new String[100][200];
    DefaultTableModel modelo;
    DefaultTableModel modeloLibros;
    DefaultTableModel modeloVentas;

    public Principal() {
        iva = 0;
        initComponents();
        icliente = new cliente_servicio();
        ilibro = new libro_servicio();
        iventa = new venta_servicio();
        limpiarClientes();
        limpiarLibros();
        limpiarVentas();
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloAgregarCliente = new javax.swing.JLabel();
        lblRutCliente = new javax.swing.JLabel();
        txtRutCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomCliente = new javax.swing.JTextField();
        lblApPaternoCli = new javax.swing.JLabel();
        txtApPaternoCli = new javax.swing.JTextField();
        txtApMaternoCli = new javax.swing.JTextField();
        lblApMaternoCli = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccionCli = new javax.swing.JTextField();
        lblCorreoCli = new javax.swing.JLabel();
        txtCorreoCli = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTituloProducto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodLibro = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnGuardarLibro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        btnLimpiarLibros = new javax.swing.JButton();
        btnModificarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnBuscarLibro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboLibros = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodVenta = new javax.swing.JTextField();
        btnGuardarVenta = new javax.swing.JButton();
        btnModificarVenta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnEliminarVenta = new javax.swing.JButton();
        btnLimpiarVenta = new javax.swing.JButton();
        btnBuscarVenta = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/975793fff4eb682dcc396c2885a13f2f.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        lblTituloAgregarCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloAgregarCliente.setText("Agregar Cliente");

        lblRutCliente.setText("Rut: ");

        jLabel1.setText("Nombre:");

        lblApPaternoCli.setText("A. Paterno:");

        lblApMaternoCli.setText("A. Materno:");

        lblDireccion.setText("Dirección: ");

        lblCorreoCli.setText("Correo:");

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/plus.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/search.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/nuevo.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/compose (1).png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Correo:");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblCorreoCli)
                    .addComponent(lblDireccion)
                    .addComponent(lblApPaternoCli)
                    .addComponent(jLabel1)
                    .addComponent(lblRutCliente)
                    .addComponent(lblApMaternoCli))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApMaternoCli)
                    .addComponent(txtRutCliente)
                    .addComponent(txtNomCliente)
                    .addComponent(txtApPaternoCli)
                    .addComponent(txtDireccionCli)
                    .addComponent(txtCorreoCli, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiar)
                            .addComponent(btnAgregarCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloAgregarCliente)
                .addGap(400, 400, 400))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTituloAgregarCliente)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutCliente)
                    .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApPaternoCli)
                            .addComponent(txtApPaternoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApMaternoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApMaternoCli))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccionCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(288, 288, 288)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoCli)
                    .addComponent(txtCorreoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        lblTituloProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloProducto.setText("Registrar Libros");

        jLabel3.setText("Codigo Libro:");

        jLabel4.setText("ISBN:");

        jLabel5.setText("Titulo:");

        jLabel6.setText("Año:");

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLibros);

        btnGuardarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/plus.png"))); // NOI18N
        btnGuardarLibro.setText("Agregar");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });

        jLabel7.setText("Autor:");

        btnLimpiarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/nuevo.png"))); // NOI18N
        btnLimpiarLibros.setText("Limpiar");
        btnLimpiarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLibrosActionPerformed(evt);
            }
        });

        btnModificarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/compose (1).png"))); // NOI18N
        btnModificarLibro.setText("Modificar");
        btnModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/delete.png"))); // NOI18N
        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        btnBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/search.png"))); // NOI18N
        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblTituloProducto))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodLibro)
                                    .addComponent(txtIsbn)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(txtAnio)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 252, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnGuardarLibro))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTituloProducto)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCodLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnModificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Registrar Ventas");

        jLabel9.setText("Cliente: ");

        jLabel10.setText("Libro:");

        jLabel11.setText("Cantidad:");

        jLabel12.setText("Precio:");

        jLabel13.setText("Total:");

        txtTotal.setEditable(false);

        jLabel14.setText("Codigo:");

        btnGuardarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/plus.png"))); // NOI18N
        btnGuardarVenta.setText("Calcular y Agregar Venta");
        btnGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVentaActionPerformed(evt);
            }
        });

        btnModificarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/compose (1).png"))); // NOI18N
        btnModificarVenta.setText("Modificar");
        btnModificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVentaActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVentas);

        btnEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/delete.png"))); // NOI18N
        btnEliminarVenta.setText("Eliminar");
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });

        btnLimpiarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/nuevo.png"))); // NOI18N
        btnLimpiarVenta.setText("Limpiar");
        btnLimpiarVenta.setToolTipText("");
        btnLimpiarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarVentaActionPerformed(evt);
            }
        });

        btnBuscarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img/search.png"))); // NOI18N
        btnBuscarVenta.setText("Buscar");
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad)
                            .addComponent(cboCliente, 0, 114, Short.MAX_VALUE)
                            .addComponent(cboLibros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio)
                            .addComponent(txtTotal)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodVenta)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarVenta)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLimpiarVenta)
                                    .addComponent(btnModificarVenta))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarVenta)
                                .addGap(16, 16, 16)
                                .addComponent(btnEliminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel8)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminarVenta)
                                .addComponent(btnBuscarVenta))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnModificarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarVenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarVenta))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        try {
            Cliente c = new Cliente();
            c.setRut(txtRutCliente.getText());
            c.setNombre(txtNomCliente.getText());
            c.setAppaterno(txtApPaternoCli.getText());
            c.setApmaterno(txtApMaternoCli.getText());
            c.setDireccion(txtDireccionCli.getText());
            c.setCorreo(txtCorreo.getText());
            MSG msg = icliente.CrearCliente(c);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Cliente Agregado");
                limpiarClientes();
                cargarDatos();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en ingresar al cliente");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        try {

            String rut = JOptionPane.showInputDialog(null, "Ingrese el RUT del cliente:", "Buscar Cliente", JOptionPane.QUESTION_MESSAGE);
            if (rut == null || rut.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un RUT válido.");
                return;
            }

            Cliente cli = icliente.cliente(rut.trim());
            if (cli == null) {
                JOptionPane.showMessageDialog(null, "No hay cliente asociado a ese RUT.");
            } else {

                txtRutCliente.setText(cli.getRut());
                txtNomCliente.setText(cli.getNombre());
                txtApPaternoCli.setText(cli.getAppaterno());
                txtApMaternoCli.setText(cli.getApmaterno());
                txtDireccionCli.setText(cli.getDireccion());
                txtCorreo.setText(cli.getCorreo());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarClientes();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        try {
            Cliente c = new Cliente();
            c.setRut(txtRutCliente.getText());
            c.setNombre(txtNomCliente.getText());
            c.setAppaterno(txtApPaternoCli.getText());
            c.setApmaterno(txtApMaternoCli.getText());
            c.setDireccion(txtDireccionCli.getText());
            c.setCorreo(txtCorreo.getText());
            MSG msg = icliente.ModificarCliente(c);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Cliente Modificado");
                limpiarClientes();
                cargarDatos();
                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en ingresar al cliente");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            String rut = JOptionPane.showInputDialog(null, "Ingrese el RUT del cliente:", "Buscar Cliente", JOptionPane.QUESTION_MESSAGE);
            MSG msg = icliente.EliminarCliente(rut);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            if (msg.getId_MSG() == 1) {
                limpiarClientes();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algunos de los campos ingresados no corresponde");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // TODO add your handling code here:

        try {
            Libro l = new Libro();
            l.setCodLibro(txtCodLibro.getText());
            l.setIsbn(txtIsbn.getText());
            l.setAutor(txtAutor.getText());
            l.setTitulo(txtTitulo.getText());
            l.setAnio(Integer.parseInt(txtAnio.getText()));
            MSG msg = ilibro.CrearLibro(l);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Libro Agregado");
                limpiarLibros();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en agregar Libro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnLimpiarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLibrosActionPerformed
        // TODO add your handling code here:
        limpiarLibros();
    }//GEN-LAST:event_btnLimpiarLibrosActionPerformed

    private void btnModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLibroActionPerformed
        // TODO add your handling code here:
        try {
            Libro l = new Libro();
            l.setCodLibro(txtCodLibro.getText());
            l.setIsbn(txtIsbn.getText());
            l.setAutor(txtAutor.getText());
            l.setTitulo(txtTitulo.getText());
            l.setAnio(Integer.parseInt(txtAnio.getText()));
            MSG msg = ilibro.ModificarLibro(l);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Libro Modificado");
                limpiarLibros();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en modificar Libro");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
        try {
            String codLibro = JOptionPane.showInputDialog(null, "Ingrese el Codigo Libro", "Buscar Libro", JOptionPane.QUESTION_MESSAGE);
            MSG msg = ilibro.EliminarLibro(codLibro);
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            if (msg.getId_MSG() == 1) {
                limpiarLibros();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algunos de los campos ingresados no corresponde");
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:

        try {
            String codLibro = JOptionPane.showInputDialog(null, "Ingrese el código del libro:", "Buscar Libro", JOptionPane.QUESTION_MESSAGE);
            if (codLibro == null || codLibro.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un codigo válido.");
                return;
            }
            Libro lib = ilibro.libro(codLibro.trim());
            if (lib == null) {
                JOptionPane.showMessageDialog(null, "No hay libros asociado a ese codigo.");
            } else {
                txtCodLibro.setText(lib.getCodLibro());
                txtIsbn.setText(lib.getIsbn());
                txtAutor.setText(lib.getAutor());
                txtTitulo.setText(lib.getTitulo());
                txtAnio.setText(Integer.toString(lib.getAnio()));

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVentaActionPerformed
        // TODO add your handling code here:
        try {
            Venta ven = new Venta();

            ven.setCodVenta(txtCodVenta.getText());
            ven.setCliente(cboCliente.getSelectedItem().toString());
            ven.setLibro(cboLibros.getSelectedItem().toString());
            ven.setCantidad(Integer.parseInt(txtCantidad.getText())); 
            ven.setNeto(Integer.parseInt(txtPrecio.getText())); 

            // Aqui realizamos el calculo para el IVA. :D
            int precio = Integer.parseInt(txtPrecio.getText());
            int iva = (int) (precio * 0.19); // Calcular IVA (19%)
            int total = precio + iva;

            ven.setTotal(total);
            txtTotal.setText(String.valueOf(total));
            MSG msg = iventa.CrearVenta(ven);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Venta Registrada");
                limpiarVentas();
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Por favor, verifica que los valores ingresados sean numéricos.");
        } catch (Exception ex) {

            System.out.println("Error " + ex.getMessage());
        }

    }//GEN-LAST:event_btnGuardarVentaActionPerformed

    private void btnModificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVentaActionPerformed
        // TODO add your handling code here:
        try {

            Venta ven = new Venta();

            ven.setCodVenta(txtCodVenta.getText());
            ven.setCliente(cboCliente.getSelectedItem().toString());
            ven.setLibro(cboLibros.getSelectedItem().toString());
            ven.setCantidad(Integer.parseInt(txtCantidad.getText()));
            ven.setNeto(Integer.parseInt(txtPrecio.getText()));

            int precio = Integer.parseInt(txtPrecio.getText());
            int iva = (int) (precio * 0.19); // Calcular IVA (19%)
            int total = precio + iva;

            ven.setTotal(total);
            txtTotal.setText(String.valueOf(total));
            MSG msg = iventa.ModificarVenta(ven);
            if (msg.getId_MSG() == 1) {
                JOptionPane.showMessageDialog(null, "Venta Modificada");
                limpiarVentas();
                cargarDatos();
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Por favor, verifica que los valores ingresados sean numéricos.");
        } catch (Exception ex) {

            System.out.println("Error " + ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarVentaActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        // TODO add your handling code here:

        try {
            String codVenta = JOptionPane.showInputDialog(null, "Ingrese el Codigo Venta", "Buscar Venta", JOptionPane.QUESTION_MESSAGE);
            MSG msg = iventa.EliminarVenta(codVenta);
            JOptionPane.showMessageDialog(null, "Venta Eliminada");
            if (msg.getId_MSG() == 1) {
                limpiarVentas();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algunos de los campos ingresados no corresponde");
        }
    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void btnLimpiarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarVentaActionPerformed
        // TODO add your handling code here:
        limpiarVentas();
        cargarDatos();
    }//GEN-LAST:event_btnLimpiarVentaActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        // TODO add your handling code here:

         try {

        String codVenta = JOptionPane.showInputDialog(null, "Ingrese el código de Venta:", "Buscar Venta", JOptionPane.QUESTION_MESSAGE);
        if (codVenta == null || codVenta.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un código válido.");
            return;
        }


        Venta ven = iventa.venta(codVenta.trim());


        if (ven == null) {
            JOptionPane.showMessageDialog(null, "No hay ventas asociadas a ese código.");
        } else {

            txtCodVenta.setText(ven.getCodVenta());
            txtCantidad.setText(String.valueOf(ven.getCantidad()));
            txtPrecio.setText(String.valueOf(ven.getNeto()));
            txtTotal.setText(String.valueOf(ven.getTotal()));

            String libro = ven.getLibro();
            String cliente = ven.getCliente();

            if (libro != null) {
                cboLibros.setSelectedItem(libro);
            }else{
                JOptionPane.showMessageDialog(null, "Error cargar Libro");
            }
            
            if(cliente != null){
                cboCliente.setSelectedItem(cliente);
            }else{
                JOptionPane.showMessageDialog(null, "Error cargar Cliente");
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarVentaActionPerformed

    void cargarDatos(){
         int sw = 0;
        ArrayList<Cliente> clientes = icliente.clientes();
        for (int i = 0; i < clientes.size(); i++) {
            if (sw == 0) {
                cboCliente.addItem("Seleccione");
                sw = 1;
            }
            cboCliente.addItem(clientes.get(i).getNombre());

        }
        cboCliente.setSelectedIndex(0);

        int sw2 = 0;
        ArrayList<Libro> libros = ilibro.libros();
        for (int i = 0; i < libros.size(); i++) {
            if (sw2 == 0) {
                cboLibros.addItem("Seleccione");
                sw = 2;
            }
            cboLibros.addItem(libros.get(i).getTitulo());
        }
        cboLibros.setSelectedIndex(0);
    }
    
    void limpiarVentas() {
        txtCodVenta.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtTotal.setText("");
        cboCliente.setSelectedIndex(-1);
        cboLibros.setSelectedIndex(-1);
       

        ArrayList<Venta> ventas = iventa.ventas();
        Object columnas[] = {"Cod Venta", "Cliente", "Libro", "Cantidad", "Fecha Venta", "Valor Neto", "Total"};
        DefaultTableModel modeloVenta = new DefaultTableModel(columnas, 0);
        tblVentas.setModel(modeloVenta);
        for (int i = 0; i < ventas.size(); i++) {
            Object[] dataVentas = {
                ventas.get(i).getCodVenta(),
                ventas.get(i).getCliente(),
                ventas.get(i).getLibro(),
                ventas.get(i).getCantidad(),
                ventas.get(i).getFechaVenta(),
                ventas.get(i).getNeto(),
                ventas.get(i).getTotal()
            };
            modeloVenta.addRow(dataVentas);
        }
    }

    void limpiarClientes() {
        txtApMaternoCli.setText("");
        txtApPaternoCli.setText("");
        txtCorreo.setText("");
        txtDireccionCli.setText("");
        txtNomCliente.setText("");
        txtRutCliente.setText("");

        ArrayList<Cliente> clientes = icliente.clientes();
        Object columnas[] = {"Rut", "Nombre", "Apellido", "Direccion", "Correo"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        tblClientes.setModel(modelo);

        for (int i = 0; i < clientes.size(); i++) {
            Object[] dataClientes = {clientes.get(i).getRut(),
                clientes.get(i).getNombre(),
                clientes.get(i).getAppaterno() + " " + clientes.get(i).getApmaterno(),
                clientes.get(i).getDireccion(),
                clientes.get(i).getCorreo()};
            modelo.addRow(dataClientes);
        }
    }

    void limpiarLibros() {
        txtCodLibro.setText("");
        txtIsbn.setText("");
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnio.setText("");

        ArrayList<Libro> libros = ilibro.libros();
        Object columnas[] = {"Codigo Libro", "ISBN", "Autor", "Titulo", "Anio"};

        DefaultTableModel modeloLibros = new DefaultTableModel(columnas, 0);
        tblLibros.setModel(modeloLibros);

        for (int i = 0; i < libros.size(); i++) {
            Object[] dataLibros = {
                libros.get(i).getCodLibro(),
                libros.get(i).getIsbn(),
                libros.get(i).getAutor(),
                libros.get(i).getTitulo(),
                libros.get(i).getAnio()
            };
            modeloLibros.addRow(dataLibros);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JButton btnGuardarVenta;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarLibros;
    private javax.swing.JButton btnLimpiarVenta;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarLibro;
    private javax.swing.JButton btnModificarVenta;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApMaternoCli;
    private javax.swing.JLabel lblApPaternoCli;
    private javax.swing.JLabel lblCorreoCli;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblRutCliente;
    private javax.swing.JLabel lblTituloAgregarCliente;
    private javax.swing.JLabel lblTituloProducto;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApMaternoCli;
    private javax.swing.JTextField txtApPaternoCli;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodLibro;
    private javax.swing.JTextField txtCodVenta;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoCli;
    private javax.swing.JTextField txtDireccionCli;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRutCliente;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
